[[section-introduction-and-goals]]
== Introduction and Goals

Este documento explica el proyecto realizado durante la asignatura de Arquitectura de Software. En ella se nos ha contratado para realizar un sistema web denominado Lo Map basado en la arquitectura SOLID.

Este proyecto esta desarrollado por un equipo de 5 personas.

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

El objetivo principal de este sistema es ofrecer un mapa donde los usuarios puedan guardar y situar distintos puntos de interes que ellos valoren. Los requisitos que se piden realizar en este proyecto son:

* Guardar la información en pods individuales
* Mostrar en un mapa los diferentes lugares que los usuarios quieran guardar
* Selección entre diferentes categorias para los lugares (tiendas, bares, restaurantes...)
* Los usuarios pueden acceder a información compartida por otros usuarios
* Se permite realizar filtros a las busquedas del mapa
* Se puede asociar puntuación comentarios


[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[options="header",cols="1,2"]
|===
|Objetivo|Descripción
| _Usabilidad_ | _Tener un sistema que cualquier usuario pueda utilizar fácilmente_ 
| _Descentralizado_ | _Evitar tener la información en una base de datos central para evitar problemas de seguridad con la información_
| _Privacidad_ | _Cada usuario pueda controlar su información y quien tiene acceso a ella_
| _Diseño limpio_ | _Código lo más limpio posible para facilitar su expansión y modificación_
| _Interoperabilidad_ | _Los datos creados van a poder usarse en otras aplicaciones_ 
|===

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Usuarios_ | _Posibles usuarios_ | _Una aplicación rápida, funcional y fácil de entender_
| _Profesores_ | _Profesores_ | _Un proyecto evaluable que sigua los criterios requeridos_
| _Contratador_ | _Ayuntamiento de Bruselas_ | _Una aplicación funcional que cumpla los requisitos solicitados en el contrato_
| _Equipo de desarrollo_ | _Equipo de desarrollo_ | _Saber desarrollar una aplicación con los requisitos dados y conocer mejor el funcionamiento de los principios SOLID_
|===
