[[section-solution-strategy]]
== Solution Strategy

Hemos tomado varias decisions para solucionar los distintos problemas respecto al diseño de la aplicación. Estas son:

- SOLID. Utilizaremos SOLID como método de almacenar la información de los usuarios con una gran privacidad.

- React y TypeScript. Como lenguaje para el diseño de la aplicación.

- Github. Como método de control y copia del proyecto.

- MVC. Utilizaremos un diseño de modelo-vista-controlador para el desarrollo de la aplicación y comunicación entre sus capas.

- MongoDB. Utilizaremos MongoDB como base de datos para almacenar determinada información.

[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
