[[section-runtime-view]]
== Runtime View

Estos son algunos casos de uso que se producen dentro de la aplicación y de como se desarrollan dentro de la aplicación.

[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Casos de uso Nivel 1

==== Añadir un punto al mapa
*_En este caso de uso observamos como un usuario ya registrado añade un punto nuevo en su mapa._
[plantuml,"Añadir punto",png]
----
actor "User" as user
participant "LoMap" as LoMap
database "Solid Pod" as pod

user->LoMap: AñadirPunto()
LoMap->pod: GuardarPuntoEnPOD()
LoMap->user: CargarPuntoEnMapa()
----

==== Iniciar sesión
*_En este caso de uso observamos como un usuario introduce su perfil y su contraseña para entrar en la aplicación._
[plantuml, "Iniciar sesón", png]
----
actor "User" as user
participant "LoMap" as LoMap
database "Solid Pod" as pod

user->LoMap: Entra en la pagina y escoge "Log in"
LoMap->user: Muestra la pantalla de inicio de sesion
user->LoMap: Introduce datos y slecciona iniciar sesión
LoMap->pod: Se envian los datos a al pod
alt Credenciales válidas
    LoMap->user: Muestra el mapa
else Credenciales invalidas
    LoMap->user: No permite inicio
end
----

==== Cargar mapa
*_El usuario iniciará sesión y automáticamente se cargará el mapa, para ello tiene que llamar a la clase principal y que esta escoja el mapa deseado._
[plantuml,"Cargar mapa",png]
----
actor User as user
participant "loMap" as loMap
database "Solid POD" as pod
database "Database" as data

user -> loMap :Login()
loMap -> data: compruebaDatos()
lomap <- data: confirmaDatos()
user -> loMap : eligeMapa()
loMap -> pod: llamaAMapa()
lomap <- pod : CargaMapa()
----

==== Añadir un amigo
*_En este caso de uso podemos observar el flujo seguido para añadir a un amigo nuestro pod de SOLID._
[plantuml,Añadir amigo,png]
----
@startuml
autonumber

actor User as user
participant "loMap" as loMap
database "Solid POD" as pod

user -> loMap : AñadirAmigo()
user <- loMap: listaAmigos()
user -> loMap : IntroducePodId()
loMap -> pod: buscaPodId()
loMap <- pod: AñadeAmigoId()
user <- loMap : listaAmigos()
alt Id de amigo no encontrado
    loMap <- pod: noExisteId()
    user <- loMap : listaAmigos()
else amigo ya añadido
     loMap <- pod: amigoYaAñadido()
    user <- loMap : listaAmigos()
end
@enduml
----

==== Eliminar un amigo
*_En este caso de uso observamos como eliminar un amigo de nuestro pod._
[plantuml,"Eliminar amigo",png]
----
actor User as user
participant "loMap" as loMap
database "Solid POD" as pod

user -> loMap : EliminarAmigo()
loMap -> pod: listaAmigos()
loMap -> pod : EliminarAmigo()
user -> loMap : IntroducePodId()
loMap -> pod: buscaPodId()
loMap -> pod: EliminaAmigoId()
----

=== Casos de uso Nivel 2

==== Añadir un punto al mapa
*_En este caso de uso observamos como un usuario ya registrado añade un punto nuevo en su mapa y como se comunica con el POD privado para actualizar la información._
[plantuml,"Añadir punto lvl2",png]
----
actor "User" as user
participant "LoMap" as LoMap
Participant "POD Server" as server
database "User POD" as pod

user->LoMap: AñadirPunto()
LoMap->server: ComprobarEstadoDeSesion()
LoMap->server: GuargarPunto()
Server->POD: GuardarPunto()
POD->LoMap: ConfirmarRecepcion()
LoMap->user: CargarPuntoEnMapa()
----

==== Añadir un amigo
*_En este caso de uso observamos como añadir un amigo a nuestro pod y como se actualiza la información en ambos pods._
[plantuml,"Eliminar amigo lvl2",png]
----
actor User as user
participant "loMap" as loMap
participant "POD Server" as server
database "User POD" as userp
database "Friend POD" as friendp

user -> loMap : AñadirAmigo()
loMap -> server: listaAmigos()
server -> userp: listaAmigos()
loMap -> server: buscaPodId()
server -> userp: buscaPodId()
loMap -> server : AñadirAmigo(idUser, idAmigo)
server -> userp : AñadirAmigo(idUser, idAmigo)
server -> friendp : AñadirAmigo(idUser, idAmigo)
----

==== Eliminar un amigo
*_En este caso de uso observamos como eliminar un amigo de nuestro pod y como se actualiza la información en ambos pods._
[plantuml,"Eliminar amigo lvl2",png]
----
actor User as user
participant "loMap" as loMap
participant "POD Server" as server
database "User POD" as userp
database "Friend POD" as friendp

user -> loMap : EliminarAmigo()
loMap -> server: listaAmigos()
server -> userp: listaAmigos()
loMap -> server: buscaPodId()
server -> userp: buscaPodId()
loMap -> server : EliminarAmigo(idUser, idAmigo)
server -> userp : EliminarAmigo(idAmigo)
server -> friendp : EliminarAmigo(idUser)
----