[[section-design-decisions]]
== Design Decisions

Hemos tomado varias decisiones arquitectónicas respecto al diseño de la aplicación. Estas son:

- SOLID. Utilizaremos SOLID como método de almacenar la información de los usuarios con una gran privacidad.

- React y TypeScript. Como lenguaje para el diseño de la aplicación.

- MVC. Utilizaremos un diseño de modelo-vista-controlador para el desarrollo de la aplicación y comunicación entre sus capas.

- MongoDB. Utilizaremos MongoDB como base de datos para almacenar determinada información.

[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
