[[section-design-decisions]]
== Design Decisions
=== Decisiones generales
Durante las diferentes semanas de trabajo hemos tenido que tomar diferentes decisiones importantes para encaminar el proyecto,
Aunque la mayoría están reflejadas en nuestra wiki, vamos a hacer un análisis global de todas ellas, decidimos no incluir gitHub u otras herramientas como SonarCloud ya que
no fue una decisión del equipo como tal:
* Utilizaremos SOLID, un proyecto de descentralización de datos
* Utilizaremos react para la interfaz
* Utilizaremos Typescript, un lenguaje muy similar a javascript
* Seguiremos el MVC(Modelo Vista Controlador) un patrón de arquitectura muy común
* Node.js será nuestro programa para ejecutar la aplicación junto a express
* Nos decantamos por mongoDb para nuestra base de datos
* Utilizamos MapBox para las APIs de los mapas
=== Problemas 
* Necesitamos aprender a usar estas nuevas herramientas de trabajo. SOLID y sus PODs, react, MapBox y TypeScript son tecnologías completamente
nuevas para la mayoría de los participantes del grupo
* Un problema que tiene node.js es su dificultad para entender su código, y su tecnología moderna puede ser un problema a la hora de buscar
información
* Hemos tenido problemas a la hora de mezclar la tecnología typescript y react con mapBox

=== Consecuencias
* Hemos tenido que indagar mucho para aprender a usar las nuevas tecnologías, tanto para las que no sabíamos cómo utilizar como para
las que sí podemos aprender a utilizar más fácilmente, pero su información en internet es escasa, perdiendo tiempo
* Para utilizar los mapas, hemos usado javascript para evitar los errores que teníamos con Mapbox y con código .tsx

=== Decisiones concretas
* Utilizamos javascript de manera puntual
* Reestructuración de proyecto: Como un compañero de equipo dejó la asignatura, tuvimos que volver a repartir el trabajo para cada miembro

[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
