[[section-technical-risks]]
== Risks and Technical Debts
El principal problema al que nos enfrentamos es a un nuevo entorno de trabajo, el cual tiene una tecnología completamente nueva para la mayoría de integrantes del grupo lo que hace que sea complicado el inicio.
Y también hay que tener en cuenta el tiempo que tenemos y el resto de asignaturas de la universidad. Aquí hay una tabla que refleja los principales problemas.
[options="header",cols="1,2,2"]
|===
|Riesgo|Problema|Solución

| *Nueva tecnología* | _Dificultades a la hora de empezar el proyecto y con la compatibilidad entre herramientas._ | _Practicar y pedir ayuda a profesores o alumnos que cursaron la materia_

| *Tiempo* | _El resto de asignaturas nos quita mucho tiempo lo cual puede hacer que lleguemos forzados a las entregas._ | _Mejorar nuestra organización personal y coordinar horarios con compañeros_

| *Problemas de equipo* | _Trabajar en equipo siempre supone algún problema, aquí no va a ser una excepción._ | _Reuniones de equipo, organización y si hay algún problema contatar con el profesor_

| *GitHub* | _Problemas con el manejo de gitHub e incluso pérdidas de archivos_ | _Tener muy claro lo que hace cada función de git, y si hay dudas hablar con profesores_

<<<<<<< HEAD
Existen una variedad de riesgos a la hora de desarrollar el proyecto LoMap con los que tendremos que lidiar:

- Utilizar el principio SOLID. Utilizar información descentralizada hace más complicado el desarrollo del proyecto respecto a lo que sería utilizar una base de datos propia.

- Mantener la interoperabilidad de los datos. Utilizar un estándar común que puede dificultar el desarrollo para poder compartir y utilizar los datos con otras aplicaciones.

- Una base de datos en MongoDB. Utilizar una base de datos propia para guardar algunos datos, pero que puede producir complicaciones a la hora de identificar correctamente que datos se deben guardar en el pod y cuales en la base de datos.

También hay otros riesgos que son la utilización de tecnologías con las que no estamos acostumbrados y que aprenderemos a usar correctamente a lo largo del desarrollo del proyecto.

=======
 
>>>>>>> documentación-ivan2
|===


=== Technical Debts
Al ser un proyecto que hemos empezado de 0, nos ha sido fácil tener una arquitectura escalable sin deuda técnica.
Quizá a la hora de hacer la interoperabilidad de la aplicación no se ha escogido la mejor opción y sí la más facil de aprender y de 
que todo el mundo la pueda utilizar para ahorrar problemas y no perder mucho el tiempo en ello, lo cuál haya generado un poco de deuda técnica.


